// 12+ sample products spread across multiple categories.
// Real product photography (hotlinked from Unsplash, no file uploads needed).
// Every URL below was verified to return a real, category-appropriate photo.
const products = [
  {
    name: 'Wireless Bluetooth Headphones',
    description: 'Over-ear wireless headphones with active noise cancellation, 30-hour battery life and a comfortable memory-foam fit.',
    price: 3999,
    discountPrice: 2999,
    category: 'Electronics',
    brand: 'SoundWave',
    images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=700&h=700&fit=crop&q=80&auto=format'],
    stock: 25,
    isFeatured: true,
    isBestSeller: true,
  },
  {
    name: 'Smart Fitness Watch',
    description: 'Track heart rate, sleep and workouts with this water-resistant smartwatch featuring a 7-day battery life.',
    price: 4999,
    discountPrice: 3999,
    category: 'Electronics',
    brand: 'FitPro',
    images: ['https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=700&h=700&fit=crop&q=80&auto=format'],
    stock: 18,
    isFeatured: true,
  },
  {
    name: 'Portable Bluetooth Speaker',
    description: 'Compact speaker with rich bass, IPX7 waterproofing and 12 hours of playtime, perfect for outdoor use.',
    price: 2499,
    discountPrice: 1899,
    category: 'Electronics',
    brand: 'SoundWave',
    images: ['https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=700&h=700&fit=crop&q=80&auto=format'],
    stock: 30,
    isBestSeller: true,
  },
  {
    name: 'Mechanical Gaming Keyboard',
    description: 'RGB backlit mechanical keyboard with hot-swappable switches, built for gaming and long typing sessions.',
    price: 5499,
    discountPrice: 0,
    category: 'Electronics',
    brand: 'KeyForge',
    images: ['https://images.unsplash.com/photo-1595044426077-d36d9236d54a?w=700&h=700&fit=crop&q=80&auto=format'],
    stock: 15,
  },
  {
    name: "Men's Classic Cotton T-Shirt",
    description: 'Breathable 100% cotton t-shirt with a relaxed fit, available in everyday essential colors.',
    price: 799,
    discountPrice: 599,
    category: 'Fashion',
    brand: 'Urban Thread',
    images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=700&h=700&fit=crop&q=80&auto=format'],
    stock: 60,
    isBestSeller: true,
  },
  {
    name: "Women's Running Shoes",
    description: 'Lightweight running shoes with responsive cushioning and a breathable mesh upper for all-day comfort.',
    price: 3499,
    discountPrice: 2799,
    category: 'Fashion',
    brand: 'StrideFit',
    images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=700&h=700&fit=crop&q=80&auto=format'],
    stock: 22,
    isFeatured: true,
  },
  {
    name: 'Denim Jacket',
    description: 'Classic washed denim jacket with a comfortable regular fit, a wardrobe staple for every season.',
    price: 2999,
    discountPrice: 0,
    category: 'Fashion',
    brand: 'Urban Thread',
    images: ['https://images.unsplash.com/photo-1551537482-f2075a1d41f2?w=700&h=700&fit=crop&q=80&auto=format'],
    stock: 20,
  },
  {
    name: 'Stainless Steel Cookware Set',
    description: '5-piece stainless steel cookware set with a tri-ply base for even heating on any stovetop.',
    price: 6999,
    discountPrice: 5499,
    category: 'Home & Kitchen',
    brand: 'HomeCraft',
    images: ['https://images.unsplash.com/photo-1590794056226-79ef3a8147e1?w=700&h=700&fit=crop&q=80&auto=format'],
    stock: 12,
    isFeatured: true,
  },
  {
    name: 'Automatic Coffee Maker',
    description: 'Programmable drip coffee maker with a built-in grinder and a 12-cup glass carafe.',
    price: 4499,
    discountPrice: 3799,
    category: 'Home & Kitchen',
    brand: 'BrewMaster',
    images: ['https://images.unsplash.com/photo-1610889556528-9a770e32642f?w=700&h=700&fit=crop&q=80&auto=format'],
    stock: 16,
    isBestSeller: true,
  },
  {
    name: 'Memory Foam Pillow Set (2-Pack)',
    description: 'Ergonomic memory foam pillows with a cooling gel layer and a removable, washable cover.',
    price: 1999,
    discountPrice: 1499,
    category: 'Home & Kitchen',
    brand: 'HomeCraft',
    images: ['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=700&h=700&fit=crop&q=80&auto=format'],
    stock: 40,
  },
  {
    name: 'Yoga Mat with Carry Strap',
    description: 'Extra-thick non-slip yoga mat made from eco-friendly TPE material, includes a carry strap.',
    price: 1299,
    discountPrice: 999,
    category: 'Sports & Fitness',
    brand: 'FitPro',
    images: ['https://images.unsplash.com/photo-1592432678016-e910b452f9a2?w=700&h=700&fit=crop&q=80&auto=format'],
    stock: 35,
    isFeatured: true,
  },
  {
    name: 'Adjustable Dumbbell Set',
    description: 'Space-saving adjustable dumbbells that replace 5 pairs of weights, ideal for home workouts.',
    price: 7999,
    discountPrice: 6999,
    category: 'Sports & Fitness',
    brand: 'IronCore',
    images: ['https://images.unsplash.com/photo-1638536532686-d610adfc8e5c?w=700&h=700&fit=crop&q=80&auto=format'],
    stock: 10,
    isBestSeller: true,
  },
  {
    name: 'Insulated Water Bottle 1L',
    description: 'Double-wall vacuum insulated stainless steel bottle that keeps drinks cold for 24 hours.',
    price: 899,
    discountPrice: 699,
    category: 'Sports & Fitness',
    brand: 'IronCore',
    images: ['https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=700&h=700&fit=crop&q=80&auto=format'],
    stock: 50,
  },
  {
    name: 'Bestselling Novel Collection (Set of 3)',
    description: 'A curated bundle of three award-winning contemporary novels, perfect for book lovers.',
    price: 1499,
    discountPrice: 1199,
    category: 'Books',
    brand: 'PagePress',
    images: ['https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=700&h=700&fit=crop&q=80&auto=format'],
    stock: 28,
    isFeatured: true,
  },
];

module.exports = products;
