import React, { useState, useEffect } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Navbar as BsNavbar, Nav, Container, Form, NavDropdown, Dropdown } from 'react-bootstrap';
import useAuth from '../../hooks/useAuth';
import useCart from '../../hooks/useCart';
import notificationService from '../../services/notificationService';
import { timeAgo } from '../../utils/timeAgo';

// Remembers, per-browser, when the shopper last opened the notification
// bell - anything newer than this counts as "unread".
const SEEN_KEY = 'shopsphere_notifications_seen_at';
const TYPE_ICON = { 'new-product': 'bi-stars', sale: 'bi-tag', system: 'bi-info-circle' };

const Navbar = () => {
  const { user, isAuthenticated, isAdmin, logout } = useAuth();
  const { itemCount } = useCart();
  const [search, setSearch] = useState('');
  const navigate = useNavigate();

  const [notifications, setNotifications] = useState([]);
  const [lastSeenAt, setLastSeenAt] = useState(() => {
    try {
      return localStorage.getItem(SEEN_KEY) || '';
    } catch {
      return '';
    }
  });

  // Real notifications, generated by the backend whenever an admin adds a
  // product or drops a real discount (see productController.js) - not
  // hardcoded copy.
  useEffect(() => {
    notificationService
      .getNotifications()
      .then((res) => setNotifications(res.notifications))
      .catch(() => {}); // the bell is a nice-to-have - never break the page over it
  }, []);

  const unreadCount = notifications.filter((n) => !lastSeenAt || n.createdAt > lastSeenAt).length;

  const handleNotificationsToggle = (isOpen) => {
    if (!isOpen) return;
    const now = new Date().toISOString();
    try {
      localStorage.setItem(SEEN_KEY, now);
    } catch {
      /* private browsing / storage blocked - unread count just won't persist */
    }
    setLastSeenAt(now);
  };

  const handleSearch = (event) => {
    event.preventDefault();
    navigate(`/products${search ? `?keyword=${encodeURIComponent(search)}` : ''}`);
  };

  // Clears the session AND sends the shopper home, so it's obvious the
  // click actually did something (staying on the same listing page after
  // clearing auth state made logout look broken).
  const handleLogout = () => {
    logout();
    navigate('/');
  };

  return (
    <BsNavbar expand="lg" className="app-navbar" sticky="top">
      <Container>
        <BsNavbar.Brand as={Link} to="/" aria-label="ShopSphere home">
          ShopSphere<span>.</span>
        </BsNavbar.Brand>
        <BsNavbar.Toggle aria-controls="main-navbar" />
        <BsNavbar.Collapse id="main-navbar">
          <Nav className="nav-editorial mx-lg-auto">
            <Nav.Link as={Link} to="/products?sort=newest">New In</Nav.Link>
            <Nav.Link as={Link} to="/products?category=Fashion">Fashion</Nav.Link>
            <Nav.Link as={Link} to="/products?category=Home%20%26%20Kitchen">Home</Nav.Link>
            <Nav.Link as={Link} to="/products">Gifting</Nav.Link>
          </Nav>
          <div className="nav-actions">
            <Form className="nav-search" onSubmit={handleSearch}>
              <i className="bi bi-search" />
              <Form.Control type="search" placeholder="Search the edit" value={search} onChange={(e) => setSearch(e.target.value)} aria-label="Search products" />
            </Form>

            <Dropdown align="end" onToggle={handleNotificationsToggle}>
              <Dropdown.Toggle as="button" className="icon-action notification-button" aria-label="Notifications">
                <i className="bi bi-bell" />
                {unreadCount > 0 && <span className="notification-dot" />}
              </Dropdown.Toggle>
              <Dropdown.Menu className="notification-menu">
                <div className="notification-heading">
                  <strong>Notifications</strong>
                  {unreadCount > 0 && <span>{unreadCount} new</span>}
                </div>
                {notifications.length === 0 ? (
                  <div className="notification-empty">
                    <i className="bi bi-bell-slash"></i>
                    No notifications yet
                  </div>
                ) : (
                  notifications.map((n) => {
                    const isUnread = !lastSeenAt || n.createdAt > lastSeenAt;
                    return (
                      <Dropdown.Item
                        key={n._id}
                        as={Link}
                        to={n.product ? `/products/${n.product}` : '/products'}
                        className={isUnread ? 'is-unread' : ''}
                      >
                        <i className={`bi ${TYPE_ICON[n.type] || 'bi-bell'}`} />
                        <div>
                          <strong>{n.title}</strong>
                          <small>{n.message}</small>
                          <small>{timeAgo(n.createdAt)}</small>
                        </div>
                        {isUnread && <span className="unread-dot" aria-hidden="true" />}
                      </Dropdown.Item>
                    );
                  })
                )}
              </Dropdown.Menu>
            </Dropdown>

            <Link to="/cart" className="icon-action position-relative" aria-label={`Cart with ${itemCount} items`}>
              <i className="bi bi-bag" />
              {itemCount > 0 && <span className="cart-badge">{itemCount}</span>}
            </Link>
            {isAuthenticated ? (
              <NavDropdown title={user?.name || 'Account'} id="account-dropdown" align="end">
                <NavDropdown.Item as={Link} to="/profile">Profile</NavDropdown.Item>
                <NavDropdown.Item as={Link} to="/orders">My Orders</NavDropdown.Item>
                {isAdmin && <NavDropdown.Item as={Link} to="/admin">Admin Dashboard</NavDropdown.Item>}
                <NavDropdown.Divider />
                <NavDropdown.Item onClick={handleLogout}>Logout</NavDropdown.Item>
              </NavDropdown>
            ) : (
              <Link to="/login" className="icon-action" aria-label="Account"><i className="bi bi-person" /></Link>
            )}
          </div>
        </BsNavbar.Collapse>
      </Container>
    </BsNavbar>
  );
};

export default Navbar;
